services:
  - type: web
    name: gti-stock-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: WATCHFILES_FORCE_POLLING
        value: false
      - key: UVICORN_WATCHFILES_ENABLED
        value: false
      - key: UVICORN_RELOAD
        value: false